### ISSUE TITLE
I get this on log in when I installed this

### ISSUE THREAD

**Issue by victhebum** [astralguild/AstralAnalytics#27]
32x AstralAnalytics\Settings-Settings.lua:268: attempt to index field 'misdirects' (a nil value)
[string "@AstralAnalytics\Settings-Settings.lua"]:268: in function `method'
[string "@AstralAnalytics\libs\Events.lua"]:101: in function <AstralAnalytics\libs\Events.lua:97>

Locals:
addon = "AstralAnalytics"
(*temporary) = nil
(*temporary) = AAEvents {
 0 = <userdata>
 Unregister = <function> defined @AstralAnalytics\libs\Events.lua:54
 Register = <function> defined @AstralAnalytics\libs\Events.lua:40
 IsRegistered = <function> defined @AstralAnalytics\libs\Events.lua:68
 OnEvent = <function> defined @AstralAnalytics\libs\Events.lua:97
 NewObject = <function> defined @AstralAnalytics\libs\Events.lua:28
 GetRegisteredFunction = <function> defined @AstralAnalytics\libs\Events.lua:83
 UnregisterAll = <function> defined @AstralAnalytics\libs\Events.lua:105
 dtbl = <table> {
 }
}
(*temporary) = "ADDON_LOADED"
(*temporary) = "LoadDefaultSettings"
(*temporary) = <function> defined =[C]:-1
(*temporary) = AAEvents {
 0 = <userdata>
 Unregister = <function> defined @AstralAnalytics\libs\Events.lua:54
 Register = <function> defined @AstralAnalytics\libs\Events.lua:40
 IsRegistered = <function> defined @AstralAnalytics\libs\Events.lua:68
 OnEvent = <function> defined @AstralAnalytics\libs\Events.lua:97
 NewObject = <function> defined @AstralAnalytics\libs\Events.lua:28
 GetRegisteredFunction = <function> defined @AstralAnalytics\libs\Events.lua:83
 UnregisterAll = <function> defined @AstralAnalytics\libs\Events.lua:105
 dtbl = <table> {
 }
}
(*temporary) = "ADDON_LOADED"
(*temporary) = true
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = optionsMenu {
 0 = <userdata>
 TopLeftCorner = <unnamed> {
 }
 PixelSnapDisabled = true
 AddEntry = <function> defined @AstralAnalytics\dropdown.lua:222
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 Center = <unnamed> {
 }
 backdropInfo = <table> {
 }
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 RightEdge = <unnamed> {
 }
 dtbl = <table> {
 }
 BottomEdge = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 BottomLeftCorner = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 TopRightCorner = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 NewObject = <function> defined @AstralAnalytics\dropdown.lua:156
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
}
(*temporary) = <table> {
 option = "Bloodlust"
 value = true
 label = "Announce Bloodlust casts"
}
(*temporary) = "combatEvents"
(*temporary) = "attempt to index field 'misdirects' (a nil value)"
ADDON_NAME = "AstralAnalytics"
ADDON = <table> {
 a = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:367
 SpellRow = <table> {
 }
 modules = <table> {
 }
 baseName = "AstralAnalytics"
 IterateEmbeds = <function> defined @ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:442
 AddBuffToCategory = <function> defined @AstralAnalytics\Lists\RaidBuffs.lua:26
 icon = <table> {
 }
 HasBuff = <function> defined @Inte

**Comment by victhebum** [comment]
Also in my chat box this appears:
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
AstralAnalytics: AstralAnalytics:AddSpellToSubEvent(subEvent, spellID, spellCategory, msgString) spellID already registered 
[Error

**Comment by Khazakdk** [comment]
@victhebum Is still happening?  The latest version should address that issue.
